### PR TITLE
Audience Display Updates for FGC 2023.

### PR DESCRIPTION
**Pull request by kyle-flynn**

### CODE REVIEW

**Comment by NoahAndrews** [comment]
The score breakdown on the results screen is broken

**Comment by kyle-flynn** [comment]
MR should now be ready to go @NoahAndrews had to finish a few things.

**Review by NoahAndrews — APPROVED** [review]
I haven't noticed any issues, and the new icons are awesome

**Review by NoahAndrews — CHANGES_REQUESTED** [review]
The scoring summary should indicate that penalty points are added to the opposing alliance's score. Right now they're displayed as  if they were subtracted, even though the final scores are calculated with them added.

We can keep things clear by adding the alliance color that received the penalty to the `PENALTY` text. For example, Blue's penalty field should read `RED PENALTY`, to indicate that Red was the team who did something to deserve a penalty.

**Comment by NoahAndrews** [comment]
Do we typically display any red or yellow cards that a team received on the audience results screen? I'm not seeing them.

**Comment by kyle-flynn** [comment]
> The results screen should indicate that penalty points are added to the opposing alliance's score. Right now they're displayed as if they were subtracted, even though the final scores are calculated with them added.
> 
> One idea for how to keep things clear: add the alliance color that received the penalty to the `PENALTY` text. For example, Blue's penalty field could read `RED PENALTY`, to indicate that Red was the team who did something to deserve a penalty.

This is how it was requested last year. I'm leaving it that way.

**Comment by kyle-flynn** [comment]
> Do we typically display any red or yellow cards that a team received on the audience results screen? I'm not seeing them.

added it back in please approve

**Pull request merged**
